server:
  port: 18297

spring:
  application:
    name: spring-boot4-demo
  threads:
    virtual:
      enabled: true

sb4d:
  my_env_var1: ${MY_ENV_VAR1}

app:
  ip-query:
    base-url: ${APP_IP_QUERY_BASE_URL:https://api.bilibili.com}