### Hello
GET {{host}}/hello

### Actuator Health
GET {{host}}/actuator/health

### DotEnv - list
GET {{host}}/dotenv/list

### DotEnv - myEnvVar1
GET {{host}}/dotenv/myEnvVar1

###

### Greeting API - hello
GET {{host}}/api/greeting

### Greeting API - hello with name
GET {{host}}/api/greeting/Spring

### Greeting API - search
GET {{host}}/api/greeting/search?keyword=mono

### Greeting API - greet (POST)
POST {{host}}/api/greeting
Content-Type: application/json

{
  "name": "World"
}

###

### HttpExchange Demo - local hello
GET {{host}}/demo/http-exchange/local/hello

### HttpExchange Demo - local hello with name
GET {{host}}/demo/http-exchange/local/hello/Spring

### HttpExchange Demo - local greet
GET {{host}}/demo/http-exchange/local/greet/World

### HttpExchange Demo - local search
GET {{host}}/demo/http-exchange/local/search?keyword=spring

### HttpExchange Demo - public ip
GET {{host}}/demo/http-exchange/public/ip

###

### SSE - data
GET {{host}}/sse/data

### SSE - data retry
GET {{host}}/sse/data/retry

### Virtual Thread - info
GET {{host}}/demo/virtual-thread/info

### Virtual Thread - parallel
GET {{host}}/demo/virtual-thread/parallel?tasks=20&sleepMs=200

###

### Text Block - basic
GET {{host}}/demo/text-block/basic

### Text Block - html
GET {{host}}/demo/text-block/html?title=Spring%20Boot%204

### Text Block - json
GET {{host}}/demo/text-block/json?name=didi&age=18

### Text Block - sql
GET {{host}}/demo/text-block/sql?keyword=spring

### Text Block - escape
GET {{host}}/demo/text-block/escape

###

### Java Date localtime
GET {{host}}/datetime/test/localtime

### Java Date localdate
GET {{host}}/datetime/test/localdate

### Java Date localdatetime
GET {{host}}/datetime/test/localdatetime
